package constants

const (
	SERVICE_ERROR = "SERVICE ERROR"
	PARAM_ERROR   = "PARAM ERROR"
	NO_PERMISSION = "NO PERMISSION"

	// ACCOUNT
	ACCOUNT_NOT_EXIST       = "ACCOUNT NOT EXISTS"
	PHONE_OR_PASSWORD_ERROR = "PHONE OR PASSWORD ERROR"
	PHONE_FOAMAT_ERROR      = "PHONE FORMAT ERROR"
	PHONE_EXIST             = "PHONE EXIST"
	INVALID_ACCOUNT_ID      = "INVALID ACCOUNT ID"
	NOT_LOGIN               = "NOT LOGIN"
	INVALID_TOKEN           = "INVALID TOKEN"
	PASSWORD_ERROR          = "PASSWORD ERROR"

	// FILE
	UPLOAD_ERROR      = "UPLOAD ERROR"
	FILE_FORMAT_ERROR = "FILE FORMAT ERROR"
	FILE_OPEN_ERROR   = "FILE OPEN ERROR"

	// PLAYLIST
	PLAYLIST_NOT_EXIST          = "PLAYLIST NOT EXISTS"
	SONG_EXISTS_IN_PLAYLIST     = "SONG EXISTS IN PLAYLIST"
	FAVORITE_PLAYLIST_NOT_EXIST = "FAVORITE PLAYLIST NOT EXISTS"
	FAVORITE_PLAYLIST_EXISTS    = "FAVORITE PLAYLIST EXISTS"

	// MUSIC
	MUSIC_NOT_EXIST = "MUSIC NOT EXISTS"

	// TASK 相关错误
	TASK_NOT_EXIST        = "TASK NOT EXISTS"
	TASK_ALREADY_ACCEPTED = "TASK ALREADY ACCEPTED"
	DISTANCE_TOO_FAR      = "DISTANCE TOO FAR"
	LOCATION_REQUIRED     = "LOCATION REQUIRED"
	TASK_CREATE_FAILED    = "TASK CREATE FAILED"

	// SOS 相关错误
	SOS_NOT_EXIST          = "SOS NOT EXISTS"
	SOS_ALREADY_RESOLVED   = "SOS ALREADY RESOLVED"
	VERIFICATION_REQUIRED  = "VERIFICATION REQUIRED"
	EMERGENCY_MATCH_FAILED = "EMERGENCY MATCH FAILED"
	SOS_CREATE_FAILED      = "SOS CREATE FAILED"

	//文件相关错误
	FILE_UPLOAD_ERROR = "FILE UPLOAD ERROR"

	//评价相关
	EVALUATION_ERROR = "EVALUATION ERROR"
)
